dataset: 'gcd'
dataroot: '/home/bingzhe/dataset/german_credit'
train_csv: '/home/bingzhe/dataset/german_credit/exp1/train.csv'
test_csv: '/home/bingzhe/dataset/german_credit/exp1/test.csv'
imageSize: 224
num_classes: 2
num_folds: 4
data_workers: 16
batch_size: 64
arch: 'mlp'

log_level: 'INFO'
log_config:
  interval: 50
num_epochs: 30
work_dir: 'exp/sgd_mlp_gdc'
checkpoint_config:
  interval: 1
resume: 'exp/sgd_mlp_gdc/latest.pth'
load_from: None
lr: 0.001
momentum: 0.9
weight_decay:  0.0005
lr_config:
  policy: 'step'
  step: 5